#theme link https://github.com/pages-themes/slate/blob/master/README.md

title: Data Analytics Portfolio
description: Hi, my name is Maisy Graves and I'm studying for a Master of Science in Data Analytics.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
