title: M Graves Data Analytics Portfolio
description: This portfolio is a selection of my work samples and projects that highlight my skills and interests. If you'd like to connect or discuss a project, please don't hesitate to reach out.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
